#!/usr/bin/env bash
# number of arguments in bash: t.ly/3mZx
if [ $# -lt 4 ]
then
    echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
fi

# source: t.ly/wP8D
# 1: PATH_TO_FILE
# 2: IP
# 3: USERNAME
# 4: PATH_TO_SSH_KEY
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
