#!/usr/bin/env bash
# using sed to replace after certain string
# source: t.ly/Nqoc
sed -i '/server_name _;/a \\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# reset nginx
/etc/init.d/nginx reload
