#!/usr/bin/env bash
# script that creates a custom 404
apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a \\trewrite ^/redirect_me/* https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page " > /var/www/html/custom_404.html
echo "" >> /var/www/html/custom_404.html
sed -i "/server_name _;/ a \\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default
service nginx start
