#!/usr/bin/env bash
# link the files from enable folder to available

# delete the file to overwrite the file 
rm -rf /etc/nginx/sites-enable/default

# ln -s symbolic link 
# ln usage: ls -sf SOURCE_FILE LINK_FILE
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
