#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# You can do it by control the for with: ((i=0; i<10; i++))
# You can do it by control the for with: i in {1..10}
# You can do it by control the seq command as follows
count=10
for count in $(seq "$count")
do
	echo Holberton School
done
