#!/usr/bin/env bash
# Bash script that displays the visitor IP along with
# the HTTP status code from the Apache log file.
# AWK stands for Aho, Weinberger, and Kernighan
awk -F " " '{print $1 " " $9}' apache-access.log
