#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code, and displays this data.
# Ordered from the greatest to the lowest number of occurrences
# OCCURENCE_NUMBER IP HTTP_CODE
awk -F " " '{print $1 " " $9}' apache-access.log | uniq -c | sort -r
