#!/usr/bin/env bash
# 10 times Holberton School but for 9th displays Hi
# if [CONDITION]
# then
#	[COMMANDS]
# else
#	[COMMANDS]
#
i=0
while [ $i -lt 10 ]
do
	i=$((i+1))
	if [ $i -eq 9 ]
	then
		echo Holberton School
		echo Hi
	else
		echo Holberton School
	fi
done
