#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10
i=0
while [ $i -lt 10 ]
do
	i=$((i+1))
	if [ $i -eq 4 ]
	then
		echo bad luck
	elif [ $i -eq 8 ]
	then
		echo good luck
	else
		echo Holberton School
	fi
done
