#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20
i=0
while [ $i -lt 20 ]
do
	i=$((i+1))
	if [ $i -eq 4 ]
	then
		echo $i
		echo bad luck China
	elif [ $i -eq 8 ]
	then
		echo $i
		echo good luck Japan
	elif [ $i -eq 17 ]
	then
		echo $i
		echo good luck Italy
	else
		echo $i
	fi
done
