#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20
# using case statement
i=0
while [ $i -lt 20 ]
do
	i=$((i+1))
	case $i in
	4)
		echo $i
		echo bad luck from China
		;;
	8)
		echo $i
		echo good luck from Japan
		;;
	17)
		echo $i
		echo good luck from Italy
		;;
	*)
		echo $i
		;;
	esac
done
