#!/bin/bash
# script that enable ufw (default firewall)
# source: t.ly/g4WD
# ufW desable by default
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
# sudo ufw status --> to check status of ufw
