#!/usr/bin/env bash
# script that configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
