#!/usr/bin/env bash
# how to run nginx as non root user?
sed -i '1 i\user nginx' /etc/nginx/nginx.conf

sed -i "s/80/8080/" /etc/nginx/sites-enabled/default


chmod -R ...

# nginx must be listening on all active IPs on port 8080

#
sed
